### ISSUE TITLE
Version 0.4.0 checksum issue in archlinux.

### ISSUE THREAD

**Issue by kanakshilledar** [wireservice/leather#107]
There exists a checksum issue for this package in arch linux. ([here](https://gitlab.archlinux.org/archlinux/packaging/packages/python-leather/-/merge_requests/1).

I would like to confirm whether the v0.4.0 was re-released? Is there any difference between both the releases? 
The earlier checksum for the 0.4.0 package was `2bc92e77a2db43b0a0aabdc9ce0893d0728ce0c8098897a55e4c2244bbdc5b0f` but now the checksum is `5b4d698e97534a2600150837c2beb446278b7ef276a699768efc5488c88290c3`.

The release upgrade for this package on arch linux happened on [Feb 20, 2024](https://gitlab.archlinux.org/archlinux/packaging/packages/python-leather/-/commit/c15e46836b6a9f5d2b673626d5b0ddece88dc417) but here the actual package release was on [Feb 24, 2024](https://github.com/wireservice/leather/commit/71a0ac379b3ce1a4490a0a7378d4b584ddd0530c)

Could you please clarify on this checksum mismatch issue?

**Comment by jpmckinney** [comment]
Hmm, it’s possible the tag changed on GitHub, but on PyPI there is only ever one version of the code for a given number.

**Comment by kanakshilledar** [comment]
Was the package re-released? Why is there a checksum mismatch?

**Comment by jpmckinney** [comment]
I have no idea what ArchLinux is doing, so I can’t really debug from my end.

ArchLinux should get releases from PyPI. If it is taking releases from GitHub, that could be the error.

**Comment by jpmckinney** [comment]
You might need to report your issue to ArchLinux instead

**Comment by kanakshilledar** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/python-leather/-/merge_requests/1
I have created a PR regarding the same issue with Arch Linux.

> ArchLinux should get releases from PyPI. If it is taking releases from GitHub, that could be the error.

They are taking releases from GitHub.

**Comment by jpmckinney** [comment]
My only guess as to why it was retagged is because the release process to PyPI failed when switching over to PyPI's new Trusted Publishers workflow. The release process is trigged by a git tag, and so the git tag had to be reissued.

Like most of the Python ecosystem, we make releases to PyPI. GitHub automatically creates tar.gz files for tags, and this feature cannot be disabled. However, we make no effort to manage releases on GitHub itself.

**Comment by jpmckinney** [comment]
We can continue discussion, but I think we largely answered the question.

**Comment by alerque** [comment]
> and so the git tag had to be reissued.

Not it did not, a new tag with an incremented patch number could have been issued. Pulling a release and re-tagging it causes a lot of work for downstream packagers like me. Please don't do that. An incomplete release where some public artifacts have been pushed is merit for fixing the release process and tagging a patch release.

> ArchLinux should get releases from PyPI. If it is taking releases from GitHub, that could be the error.

There is a long history of problems pulling releases from PyPI and we're actually moving the opposite way, pulling from project sources where possible. One of the main issues is that there is no transparency or validation for artifacts posted on PyPI. We can't easily verify if the code is even the same as what appears in source repositories, the artifacts aren't signed (and they recently removed sigining mechanisms). Git sources are much easier to monitor the differences from release to release, the artifacts can be signed, they typically include test and license infor authors frequently forget to package in the PyPI manifest, etc.

**Comment by jpmckinney** [comment]
Thanks for the context. I don't anticipate needing to re-tag anything in future.
