### ISSUE TITLE
Can't set temporal scale for line graph

### ISSUE THREAD

**Issue by aepton** [wireservice/leather#53]
I have a list of tuples like:

`data = [(datetime.date(2001, 1, 1), 1000),(datetime.date(2001, 2, 1), 2000), etc...]`

and am instantiating a chart like so:

`chart = leather.Chart(title)`
`chart.set_x_scale(leather.Temporal(data[0][0], data[-1][0]))`
`chart.add_lines(data)`

But am getting the following error:

`unsupported operand type(s) for /: 'datetime.timedelta' and 'datetime.timedelta'`

Culprit appears to be on line 25 of temporal.py, in `project()`:

`pos = (value - self._min) / (self._max - self._min)`

**Comment by onyxfish** [comment]
Thanks for the bug report! I'll look into it!

**Comment by onyxfish** [comment]
This works on latest master:

```
import datetime

import leather

data = [
    (datetime.date(2001, 1, 1), 1000),
    (datetime.date(2001, 2, 1), 2000),
    (datetime.date(2001, 3, 1), 3000)
]

chart = leather.Chart('Dots')
chart.set_x_scale(leather.Temporal(data[0][0], data[-1][0]))
chart.add_line(data)
chart.to_svg('test.svg')
```

And there are tests that seem to cover this case so I think I inadvertently fixed this at some point. Closing out.
