### ISSUE TITLE
ZeroDivisionError for Columns chart with exclusively 0-values

### ISSUE THREAD

**Issue by cryzed** [wireservice/leather#66]
When changing the [columns example](http://leather.readthedocs.io/en/latest/examples.html#columns) to only have values of 0 in the data set, leather throws the following exception:

```
Traceback (most recent call last):
  File "/home/cryzed/Documents/Code/Sandbox/columns.py", line 12, in <module>
    chart.to_svg('examples/charts/columns.svg')
  File "/home/cryzed/.conda/envs/Sandbox3/lib/python3.5/site-packages/leather/chart.py", line 326, in to_svg
    group = self.to_svg_group(width, height)
  File "/home/cryzed/.conda/envs/Sandbox3/lib/python3.5/site-packages/leather/chart.py", line 281, in to_svg_group
    axes_group.append(y_axis.to_svg(canvas_width, canvas_height, y_scale, 'left'))
  File "/home/cryzed/.conda/envs/Sandbox3/lib/python3.5/site-packages/leather/axis.py", line 111, in to_svg
    projected_value = scale.project(value, range_min, range_max)
  File "/home/cryzed/.conda/envs/Sandbox3/lib/python3.5/site-packages/leather/scales/linear.py", line 23, in project
    pos = float(value - self.min) / (self.max - self.min)
ZeroDivisionError: float division by zero
```

**Comment by onyxfish** [comment]
Yep, I need to modify the domain creation to error out early if spread of the domain is 0.

**Comment by cryzed** [comment]
Just so I am not misunderstanding: will this prevent me from creating "empty" charts? I have a few hundred small files, for which I generate charts based on their contents. Sometimes it might happen that the chart's data would be 0 for every column, would leather complain in that case? If so, how do I avoid this?

**Comment by onyxfish** [comment]
It does mean that. It seems to me the correct way to handle that is probably with a try/except block. A chart without any data could still be a chart, but it's hard to see how a chart without a scale is still a chart. I'll mull it over. I might be persuaded that failing silently is the better solution.

**Comment by cryzed** [comment]
Imagine you have a script that searches a file for certain keywords. You want to display how often each keyword was found in a chart using columns. A possible scenario definitely is that all counts are 0, which should be (imho) displayable through a chart.

I'm not really a fan of catching an exception or failing silently, if possible I really would like an empty chart that actually displays information about the counts. Is this unreasonable?

**Comment by onyxfish** [comment]
Ah, I misunderstood what you were saying. In the columns example, this definitely should be possible:

```
data = [
    ('Hello', 0),
    ('How', 0),
    ('Are', 0),
    ('You', 0)
]
```

I thought you were doing this, which its less obvious how to handle:

```
data = [
    (0, 3),
    (0, 5),
    (0, 9),
    (0, 4)
]
```

I suppose in either case it would be simplest to default to the unit scale `[0,1]`.

Thanks for talking this through with me.

**Comment by cryzed** [comment]
Glad we figured it out!
