### ISSUE TITLE
Histograms

### ISSUE THREAD

**Issue by empireshades** [wireservice/leather#68]
requested.

Btw. I love this library, esp. the name. Keep up the great work!

**Comment by onyxfish** [comment]
Thanks, @jyoo!

I'm on the fence about whether or not leather is the correct place to implement logical transformations associated with charts. I had always imagined that sort of stuff would belong in [agate](http://agate.readthedocs.io/). However, if there are a lot of users who like leather, but don't want to use agate, then I may consider it.

**Comment by jpmckinney** [comment]
Closing as no bandwidth.
