### ISSUE TITLE
Missing dependency: lxml

### ISSUE THREAD

**Issue by gwk** [wireservice/leather#79]
Not sure what the required version is, but `pip install lxml` worked fine.

**Comment by onyxfish** [comment]
Hi George, were you installing with the user instructions over the [dev instructions](http://leather.readthedocs.io/en/0.3.2/install.html)? lxml is required to run the tests, but it shouldn't be required to use the library. (It is included in the dev install instrux.)

**Comment by gwk** [comment]
It's imported by __init__.

https://github.com/wireservice/leather/blob/master/leather/__init__.py#L11

Traceback (most recent call last):
  File "clips-per-episode.svg.py", line 4, in <module>
    from leather import Chart
  File "/Users/gwk/work/leather/leather/__init__.py", line 11, in <module>
    from leather.testcase import LeatherTestCase
  File "/Users/gwk/work/leather/leather/testcase.py", line 8, in <module>
    from lxml import etree
ImportError: No module named 'lxml'

**Comment by gwk** [comment]
To answer your question, I originally installed with `pip install leather`.
Now I have github forked leather and am using `pip install -e .`. My understanding is that this is equivalent to setuptools'  "develop" mode but please correct me if I'm mistaken!

**Comment by onyxfish** [comment]
Bummer, you're right. That's a bug. Will fix! Thanks for reporting!

**Comment by onyxfish** [comment]
Fixed for 0.3.4. Lxml is now only imported in `leather.TestCase` is actually used.
