### ISSUE TITLE
Leather causes warnings to be loud

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/leather#87]
These lines are at issue:

```
warnings.resetwarnings()
warnings.simplefilter('always')
```

These sorts of lines are usually wrapped in `with warnings.catch_warnings():`

To reproduce in Python 2.7:

```
pip install virtualenvwrapper
python -c 'import leather; from pkg_resources import iter_entry_points'
```

See https://github.com/wireservice/csvkit/issues/788

**Comment by dannguyen** [comment]
Is the fix as easy as putting this into [utils.py](https://github.com/wireservice/leather/blob/master/leather/utils.py#L50)? 

```python
with warnings.catch_warnings():
    warnings.resetwarnings()
    warnings.simplefilter('always')
```

I made this change in my own version of leather and the warnings have gone away. But I'm not very familiar with the `warnings` module and didn't know if this had unintended consequences. I know in the related csvkit/issues, the workaround was to create a blank `__init__.py` in the virtualenvwrapper, but I don't know how to apply that as an Anaconda user.

**Comment by jpmckinney** [comment]
Simply wrapping those lines will perhaps make the warnings more silent than intended. I'm not sure why those lines are in `utils.py`, but the solution is likely to move them into whatever method requires that change in configuration, rather than changing the configuration globally.
