### ISSUE TITLE
Trouble installing leather

### ISSUE THREAD

**Issue by miguelpaz** [wireservice/leather#88]
Any suggestions?  
I am running Python 2.7.10 on OS El Capitan 10.11.6. I get this error when I run `pip install leather`. 
> > Collecting six>=1.6.1 (from leather)
> > Using cached six-1.11.0-py2.py3-none-any.whl
> > Installing collected packages: six, leather
> > Found existing installation: six 1.4.1
> > DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
> > Uninstalling six-1.4.1:
> Exception:
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
>     prefix=options.prefix_path,
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
>     requirement.uninstall(auto_confirm=True)
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
>     paths_to_remove.remove(auto_confirm)
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
>     renames(path, new_path)
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
>     shutil.move(old, new)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
>     copy2(src, real_dst)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
>     copystat(src, dst)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
>     os.chflags(dst, st.st_flags)
> OSError: [Errno 1] Operation not permitted: '/var/folders/52/plj039q95cq2v9600053pn1c0000gn/T/pip-wffPek-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by jpmckinney** [comment]
I'm going through old issues on a project I don't officially maintain. Looks like you might have needed to use `sudo`. In any case, Python 2.7 is now end-of-life, so closing.
