### ISSUE TITLE
 Importing ABC directly from collections module was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [wireservice/leather#96]
https://bugzilla.redhat.com/show_bug.cgi?id=1792983

https://github.com/wireservice/leather/blob/d8e06a874730bf214c5adb067dcc57b52c14bcba/leather/series/category.py#L3

https://github.com/wireservice/leather/blob/d8e06a874730bf214c5adb067dcc57b52c14bcba/leather/series/base.py#L3

Thanks for the library!

**Comment by jpmckinney** [comment]
Closed by #98
